CREATE USER "TAXI";

ALTER USER "TAXI"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

GRANT CREATE SESSION, RESOURCE TO TAXI;
ALTER USER TAXI QUOTA 100M ON users;

GRANT "CONNECT" TO "TAXI" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "TAXI" WITH ADMIN OPTION;
GRANT "DBA" TO "TAXI" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "CAPTURE_ADMIN" TO "TAXI" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "CTXAPP" TO "TAXI" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_ALL" TO "TAXI" WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO "TAXI" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO "TAXI" WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO "TAXI" WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "SODA_APP" TO "TAXI" WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO "TAXI" WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO "TAXI" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_BASIC" TO "TAXI" WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO "TAXI" WITH ADMIN OPTION;
GRANT "XDBADMIN" TO "TAXI" WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO "TAXI" WITH ADMIN OPTION;

CREATE TABLE TAXI.TRIPS (
    ID NUMBER PRIMARY KEY,
    VENDOR_ID NUMBER,
    PICKUP_DATETIME TIMESTAMP,
    DROPOFF_DATETIME TIMESTAMP,
    PASSENGER_COUNT NUMBER,
    TRIP_DISTANCE NUMBER,
    RATE_CODE_ID NUMBER,
    STORE_AND_FWD_FLAG VARCHAR2(1),
    PICKUP_LOCATION_ID NUMBER,
    DROPOFF_LOCATION_ID NUMBER,
    PAYMENT_TYPE NUMBER,
    FARE_AMOUNT NUMBER,
    EXTRA NUMBER,
    MTA_TAX NUMBER,
    TIP_AMOUNT NUMBER,
    TOLLS_AMOUNT NUMBER,
    IMPROVEMENT_SURCHARGE NUMBER,
    TOTAL_AMOUNT NUMBER,
    CONGESTION_SURCHARGE NUMBER,
    RIDER_EMAIL VARCHAR2(100),
    DRIVER_EMAIL VARCHAR2(100),
    DRIVER_NAME VARCHAR2(100),
    VEHICLE_ID VARCHAR2(50),
    CAB_TYPE_ID NUMBER
);

INSERT ALL
    INTO TAXI.TRIPS (ID, VENDOR_ID, PICKUP_DATETIME, PASSENGER_COUNT, TRIP_DISTANCE, TOTAL_AMOUNT, RIDER_EMAIL, DRIVER_EMAIL, DRIVER_NAME, VEHICLE_ID, CAB_TYPE_ID) 
    VALUES (1001, 1, CURRENT_TIMESTAMP - (1/24), 2, 3.5, 15.50, 'john.kimani@example.com', 'alpha.driver@test.com', 'Alpha Driver', 'V-999', 1)
    INTO TAXI.TRIPS (ID, VENDOR_ID, PICKUP_DATETIME, PASSENGER_COUNT, TRIP_DISTANCE, TOTAL_AMOUNT, RIDER_EMAIL, DRIVER_EMAIL, DRIVER_NAME, VEHICLE_ID, CAB_TYPE_ID) 
    VALUES (1002, 2, CURRENT_TIMESTAMP - (2/24), 1, 5.2, 22.00, 'john.kimani@example.com', 'beta.driver@test.com', 'Beta Driver', 'V-888', 2)
    INTO TAXI.TRIPS (ID, VENDOR_ID, PICKUP_DATETIME, PASSENGER_COUNT, TRIP_DISTANCE, TOTAL_AMOUNT, RIDER_EMAIL, DRIVER_EMAIL, DRIVER_NAME, VEHICLE_ID, CAB_TYPE_ID) 
    VALUES (1003, 1, CURRENT_TIMESTAMP - (3/24), 4, 1.1, 8.75, 'rider.two@example.com', 'alpha.driver@test.com', 'Alpha Driver', 'V-999', 1)
    INTO TAXI.TRIPS (ID, VENDOR_ID, PICKUP_DATETIME, PASSENGER_COUNT, TRIP_DISTANCE, TOTAL_AMOUNT, RIDER_EMAIL, DRIVER_EMAIL, DRIVER_NAME, VEHICLE_ID, CAB_TYPE_ID) 
    VALUES (1004, 2, CURRENT_TIMESTAMP - (4/24), 1, 12.5, 45.00, 'rider.three@example.com', 'gamma.driver@test.com', 'Gamma Driver', 'V-777', 1)
    INTO TAXI.TRIPS (ID, VENDOR_ID, PICKUP_DATETIME, PASSENGER_COUNT, TRIP_DISTANCE, TOTAL_AMOUNT, RIDER_EMAIL, DRIVER_EMAIL, DRIVER_NAME, VEHICLE_ID, CAB_TYPE_ID) 
    VALUES (1005, 1, CURRENT_TIMESTAMP - (5/24), 3, 2.2, 11.20, 'john.kimani@example.com', 'alpha.driver@test.com', 'Alpha Driver', 'V-999', 1)
SELECT * FROM DUAL;

COMMIT;

SELECT count(*) AS TRIP_COUNT FROM TAXI.TRIPS;